export const config = {
    RPC_URL: 'https://observer.node-1.canow-jp.dev:26656',
    REST_URL: 'https://observer.node-1.canow-jp.dev',
    EXPLORER_URL: 'https://explorer.canow-jp.dev',
    STAKING_URL: 'https://omniflix.canow-jp.dev/stake',
    NETWORK_NAME: 'Canow Ledger',
    NETWORK_TYPE: 'testnet',
    CHAIN_ID: 'canow-testnet-1',
    CHAIN_NAME: 'Canow Ledger Testnet 1',
    COIN_DENOM: 'ARX',
    COIN_MINIMAL_DENOM: 'zarx',
    COIN_DECIMALS: 9,
    PREFIX: 'canow',
    COIN_TYPE: 118,
    COSMOSTAION: null,
    COINGECKO_ID: '-',
    GAS_PRICE_STEP_LOW: 25,
    GAS_PRICE_STEP_AVERAGE: 50,
    GAS_PRICE_STEP_HIGH: 100,
    FEATURES: ['ibc-transfer', 'ibc-go'],
};
